name: Upload Site

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

      - name: Building
        run: bun run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy aritfacts
        id: deployment
        uses: actions/deploy-pages@v1
